const mongoose = require('mongoose');

const teamSchema = new mongoose.Schema({
  name: { type: String, required: true, trim: true },
  hackathonId: { type: mongoose.Schema.Types.ObjectId, ref: 'Hackathon', required: true },
  captainId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  description: { type: String, default: '' },
  projectIdea: { type: String, default: '' }, // Коротко про проєкт
  lookingFor: { type: [String], default: [] }, // ['Frontend', 'Design', 'ML']
  isOpen: { type: Boolean, default: true },    // Чи шукають людей
  isAutoGenerated: { type: Boolean, default: false },
  inviteCode: { type: String, unique: true },  // Унікальний код для запрошення
  lockedAt: { type: Date, default: null },     // Коли заблоковано (за годину до старту)
  createdAt: { type: Date, default: Date.now },
  resources: [{
    title: { type: String, required: true },
    url: { type: String, required: true },
    addedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    addedByName: { type: String },
    addedAt: { type: Date, default: Date.now }
  }]
});

// Автогенерація inviteCode перед збереженням
teamSchema.pre('save', function (next) {
  if (!this.inviteCode) {
    this.inviteCode = Math.random().toString(36).substring(2, 10).toUpperCase();
  }
  next();
});

// Віртуальне поле — чи заблокована команда
teamSchema.virtual('isLocked').get(function () {
  return this.lockedAt && new Date() >= this.lockedAt;
});

module.exports = mongoose.model('Team', teamSchema);